[main]
font=monospace:size=12
width=35
lines=8
prompt= ❯  
terminal=foot

[colors]
# background
background=3b4252ff
text=d8dee9ff
prompt=88c0d0ff
placeholder=616e88ff
input=eceff4ff

# selection
selection=5e81acff
selection-text=eceff4ff
selection-match=ebcb8bff

# match highlight (unselected)
match=88c0d0ff

# border
border=4c566aff

[border]
width=1
radius=8
